Converted argument processing to bash_stub

diff --git a/bin/vmware_archive b/bin/vmware_archive
--- a/bin/vmware_archive
+++ b/bin/vmware_archive
@@ -136,46 +136,115 @@ vm_archive() {
   fi
 }
 
-main() {
-  case "$1" in
-    "-h")
-      usage
-      exit
-      ;;
-    "-v")
-      verbose=true
+# see if any arguments were passed in
+if [ $# -gt 0 ]; then
+  # if so, step through them all and pre-process them (we do this so we can 
+  # support multiple options specified together, e.g.: -abc vs. -a -b -c),
+  # GNU-style long options with alternate style values, and for easier
+  # actual handling
+  argv=()
+  while [ $# -gt 0 ]; do
+    # is this an option (e.g. starts with a dash) or an argument?
+    if [ "${1:0:1}" = "-" ]; then
+      # is it a GNU-style long option (e.g. starts with a double-dash)?
+      if [ "${1:0:2}" = "--" ]; then
+        # push the option (everything before an equals) onto argv
+        argv=("${argv[@]}" "${1%%=*}")
+
+        # is it the alternate "--long-opt=value" format? if so, make it
+        # "--long-opt value" format buy pushing the value (everything after the
+        # equals) on as a separate argument
+        case "$1" in *=*)
+          argv=("${argv[@]}" "${1##*=}") ;;
+        esac
+      # otherwise, is it multiple single options specified together?
+      elif [ ${#1} -gt 2 ]; then
+        tmp="$1"
+        # push each onto argv as single options
+        for (( i=1; i < ${#tmp}; i++ )); do
+          argv=("${argv[@]}" "-${tmp:$i:1}")
+        done
+      # otherwise, it must be a single option so just push it onto argv
+      else
+        argv=("${argv[@]}" "$1")
+      fi
       shift
-      ;;
-    "-n")
-      dry_run=true
+    # arguments just get pushed onto argv in order too
+    else
+      argv=("${argv[@]}" "$1")
       shift
-      ;;
-    "-V")
-      version
-      exit
-      ;;
-  esac
+    fi
+  done
+  argc=${#argv[@]}
 
-  source="$1"
-  destination="$2"
-  if [ -z "$source" ]; then
-    echo "ERROR! A source VM or path to VMs must be provided! Exiting."
-    exit 1
-  fi
-  if [ -z "$destination" ]; then
-    echo "ERROR! A destination path must be provided! Exiting."
-    exit 1
-  fi
+  # now that we've pre-processed the options, go through them all for real
+  for (( i=0; i<$argc; i++ )); do
+    # is this an option (e.g. starts with a dash) or an argument?
+    if [ "${argv[$i]:0:1}" = "-" ]; then
+      case "${argv[$i]}" in
+        # see if the user intended us to run in verbose mode
+        "-v" | "--verbose")
+          verbose=true
+          ;;
+        # see if the user requested help
+        "-h" | "--help")
+          usage
+          exit
+          ;;
+        # see if the user requested the version
+        "-V" | "--version")
+          version
+          exit
+          ;;
+        "-n" | "--dry-run")
+          dry_run=true
+          ;;
+        # handle other options
+          
+        # unknown option
+        *)
+          echo "$tool: Unknown option '$1'!"
+          exit 1
+          ;;
+      esac
+    # handle arguments
+    else
+      # one would normally handle arguments here
 
-  if [[ "$source" =~ \.vmwarevm$ ]]; then
-    if $verbose; then echo "Archiving single VM '${source}' to '${destination}'..."; fi
-    vm_archive "$source" "$destination"
-  else
-    if $verbose; then echo "Archiving VMs from '${source}' to '${destination}'..."; fi
-    while IFS= read -r line; do
-      vm_archive "$line" "$destination"
-    done <<< "$(find "${source%/}" -type d -iname "*.vmwarevm")"
-  fi
-}
+      # handle source & destination arguments
+      if [ "$(( argc - i ))" -eq 2 ]; then
+        source="${argv[$i]}"
+        (( i++ ))
+        destination="{argv[$i]}"
+      else
+	echo "ERROR! Incorrect number of arguments!"
+        usage
+        exit 1
+      fi
+    fi
+  done
+else
+  echo "No options or arguments were specified!"$'\n'
+  usage
+  exit 1
+fi
 
-main "$@"
+if [ -z "$source" ]; then
+  echo "ERROR! A source VM or path to VMs must be provided! Exiting."
+  exit 1
+fi
+if [ -z "$destination" ]; then
+  echo "ERROR! A destination path must be provided! Exiting."
+  exit 1
+fi
+
+if [[ "$source" =~ \.vmwarevm$ ]]; then
+  if $verbose; then echo "Archiving single VM '${source}' to '${destination}'..."; fi
+  vm_archive "$source" "$destination"
+else
+  if $verbose; then echo "Archiving VMs from '${source}' to '${destination}'..."; fi
+  while IFS= read -r line; do
+    vm_archive "$line" "$destination"
+  done <<< "$(find "${source%/}" -type d -iname "*.vmwarevm")"
+fi
+
